experiment:
  category: Focal Term
  fold_id: 3
  model_checkpoint: nlpaueb/legal-bert-base-uncased
hyperparams:
  epochs: 20
  learning_rate: 2e-5
  batch_size: 16

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      ++experiment.category: Direct\ Quote,Focal\ Term,Metalinguistic\ Cue,Legal\ Source
      ++experiment.fold_id: 0,1,2,3
      ++experiment.model_checkpoint: bert-base-cased,nlpaueb/legal-bert-base-uncased
  sweep:
    dir: tmp


